package cronjobs

import "github.com/pocketbase/pocketbase"

func RegisterCronJobs(app *pocketbase.PocketBase) {
	modifyPendingAndOnHoldInternalOrdersOlderThan5Days(app)
	assignStaffToCompleteConfirmedAndProcessingOrdersThatHaveAllInternalOrdersCancelledUpdatedMoreThan3DaysAgo(app)
	assignStaffToCompleteUnfinishedOrdersUpdatedMoreThan3DaysAgo(app)
}
