package cronjobs

import pocketbase "github.com/AlperRehaYAZGAN/postgresbase"

func RegisterCronJobs(app *pocketbase.PocketBase) {
	modifyPendingAndOnHoldInternalOrdersOlderThan5Days(app)
	assignStaffToCompleteConfirmedAndProcessingOrdersThatHaveAllInternalOrdersCancelledUpdatedMoreThan3DaysAgo(app)
	assignStaffToCompleteUnfinishedOrdersUpdatedMoreThan3DaysAgo(app)
}
